### ISSUE TITLE
Cannot enable pseudo GUI mode

### ISSUE THREAD

**Issue by jmf1988** [jaseg/python-mpv#102]
I  tried to enable it with this options:
player.include = '/etc/mpv'
player.player_operation_mode = 'pseudo-gui'
player.profile = 'pseudo-gui'

but it did not work, how I can enable it?

**Comment by McSinyx** [comment]
You can try initializing `MPV` using `player_operation_mode='pseudo-gui', script_opts='osc-layout=box,osc-seekbarstyle=bar,osc-deadzonesize=0,osc-minmousemove=3'` as described [here](https://unix.stackexchange.com/questions/544029/what-is-the-location-of-the-settings-file-for-the-mpv-on-screen-controller-in-ne).

**Comment by jmf1988** [comment]
> You can try initializing `MPV` using `player_operation_mode='pseudo-gui', script_opts='osc-layout=box,osc-seekbarstyle=bar,osc-deadzonesize=0,osc-minmousemove=3'` as described [here](https://unix.stackexchange.com/questions/544029/what-is-the-location-of-the-settings-file-for-the-mpv-on-screen-controller-in-ne).

Thanks, it leaded me to the solution that was to simply pass player.osc=True, however I do like more the old GUI, using it from now on. 
I think this should be in the README file, pseudo-gui it is disabled because osc is by default, at least in my case under Debian.

**Comment by McSinyx** [comment]
`osc` seems to be passable to MPV init as well, e.g. `player = mpv.MPV(player_operation_mode='pseudo-gui', script_opts='osc-layout=box,osc-seekbarstyle=bar,osc-deadzonesize=0,osc-minmousemove=3', input_default_bindings=True, input_vo_keyboard=True, osc=True)`.

> I think this should be in the README file, pseudo-gui it is disabled because osc is by default, at least in my case under Debian.

Which README do you mean?  BTW pseudo GUI refers to the old (as in *replaced by new one*), so... unless you meant that you need to manually enable `osc` for libmpv, then generally every UX feature are disabled by libmpv by default I think.  It was a bit confusing for me when I first tried to use this too.

**Comment by jaseg** [comment]
The line from @McSinyx works for me, and shows the old-style GUI. I've added a code example to the README in c1df201 documenting how to use both old and new GUI modes.

**Comment by jmf1988** [comment]
> `osc` seems to be passable to MPV init as well, e.g. `player = mpv.MPV(player_operation_mode='pseudo-gui', script_opts='osc-layout=box,osc-seekbarstyle=bar,osc-deadzonesize=0,osc-minmousemove=3', input_default_bindings=True, input_vo_keyboard=True, osc=True)`.
> 
> > I think this should be in the README file, pseudo-gui it is disabled because osc is by default, at least in my case under Debian.
> 
> Which README do you mean? BTW pseudo GUI refers to the old (as in _replaced by new one_), so... unless you meant that you need to manually enable `osc` for libmpv, then generally every UX feature are disabled by libmpv by default I think. It was a bit confusing for me when I first tried to use this too.

pseudo GUI is the on screen playback controls, the one with the icons the status bar, volume, etc that shows by default in mpv when you move the mouse above the window. Without explicitly enabling osc with osc=True I just see the video and when pressing some keys the related on screen text but that is it.
Yes, to enable the old default pseudo GUI you have to pass it when initializing or it does not work, but osc can be enabled later with player.osc=True.

**Comment by jmf1988** [comment]
> The line from @McSinyx works for me, and shows the old-style GUI. I've added a code example to the README in [c1df201](https://github.com/jaseg/python-mpv/commit/c1df201b26bb1481e273bbb5043d483106ede191) documenting how to use both old and new GUI modes.
Awesome, thank you for the fast response.
