### ISSUE TITLE
Able to remove vocal of song? 

### ISSUE THREAD

**Issue by cherisetan93** [jaseg/python-mpv#105]
Hi, thanks for sharing your work. Will like to ask if it is possible to remove vocal of song? Have been trying a few ways but it was not successful.

Eg pan="stereo|c0=c0|c1=-1*c1"

**Comment by jaseg** [comment]
python-mpv is just a thin wrapper around libmpv, the library version of [mpv-player/mpv](https://github.com/mpv-player/mpv). In general anything that works on the mpv command line should also work with python-mpv. You could try it out with mpv first, then translate it to using python-mpv. If you find anywhere command line mpv and python-mpv behave differently please report :)
