### ISSUE TITLE
Please sign future tags

### ISSUE THREAD

**Issue by baldurmen** [jaseg/python-mpv#107]
Hi!

Thanks for this project, it's really neat. I'm currently in the process of [packaging this library in Debian](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=955190) so people can use it more easily.

Would it be possible to start signing your git tags and publish your GPG public key somewhere? It would make it much more easier to verify updates do come from you.

Thanks again for your time,

**Comment by jaseg** [comment]
I've signed the latest release tag [v0.4.6](https://github.com/jaseg/python-mpv/releases/tag/v0.4.6) and I'll try to remember doing that for future tags as well. The key fingerprint is 
`E36F75307F0A0EC2D145FF5CED7A208EEEC76F2D` and the full public key block can be found at https://github.com/jaseg.gpg
