### ISSUE TITLE
Simple example on headless Raspbian

### ISSUE THREAD

**Issue by majuss** [jaseg/python-mpv#109]
So I tried this really simple audio example on mi Pi:
```python
import mpv
player = mpv.MPV()
player.play('http://rbb-fritz-live.cast.addradio.de/rbb/fritz/live/mp3/128/stream.mp3')
```
But nothing happens at all. Via the cli it works fine!

I don't understand how to simply playback audio without any GUI etc.

**Comment by McSinyx** [comment]
> But nothing happens at all.

Because be the script reaches the end before playback finishes.  Probably the documentation is not clear but you'll need to `player.wait_for_playback()` to, ehm, wait for playback.

**Comment by majuss** [comment]
Wow... thank you very much! I can't find any kind of documentation?
How can I retrieve for example the icy-tags from mp3 streams?

**Comment by McSinyx** [comment]
> Wow... thank you very much! I can't find any kind of documentation?

You're welcome.  The suggestion actually comes from the readme if you scroll down a bit further (I haven't really use this library for a while).

> How can I retrieve for example the icy-tags from mp3 streams?

I'm not even sure how to do that in mpv front-end.  Can you provide more information?

**Comment by majuss** [comment]
If I run it in CLI mode with --quiet the mp3 stream is outputting strings like: ` icy-title: Fritz 14:00 - 16:00 mit Timm Lindenau`. Now I just extract them with `.find()` from the message log.

**Comment by jaseg** [comment]
You can access all MPV properties ( https://mpv.io/manual/master/#properties ) as attributes on the player object. What you're looking for is the `metadata` property:

```python
In [4]: player.metadata                                                         
Out[4]: 
{'icy-br': '128',
 'icy-description': 'fritz',
 'icy-name': b'Fritz vom rbb live h\xf6ren - www.fritz.de (c) Rundfunk Berlin-Brandenburg',
 'icy-private': '1',
 'icy-pub': '0',
 'icy-url': 'http://www.fritz.de',
 'icy-title': 'It’s Fritz'}
```

**Comment by majuss** [comment]
Thank you that's exactly what I was looking for! Is there also an easy way to fork the player thread to the background? Or should I use the python threading lib?

**Comment by McSinyx** [comment]
@majuss, base on my experience, `threading` *just work* with python-mpv.

**Comment by jaseg** [comment]
Threading should just work. Ideally try to do all access to the MPV object from the same thread it was created in. As far as I remember, for certain functions mpv doesn't like it if you call them across threads (it will return a legible error message in that case).

**Comment by majuss** [comment]
So threading is working really good and also the metadata extraction isn't a problem anymore. One of my last obstacles is the playback of multiple streams, something like that:
```python
player.play("http://rbb-fritz-live.cast.addradio.de/rbb/fritz/live/mp3/128/stream.mp3", "http://st01.dlf.de/dlf/01/128/mp3/stream.mp3")
```
But I only want to have one active at the same time, so basically a playlist made out of URLs. In the documentation I found: https://mpv.io/manual/master/#per-file-options that states I can append them, but it doesn't work with the python lib that way.

Thank you guys fo all the help, much appreciated.

**Comment by jaseg** [comment]
This seems to be a race condition internal to mpv, tracked in upstream issue [#7543](https://github.com/mpv-player/mpv/issues/7543). The issue is that the new playlist entries are added before the mpv core has fully initialized. The following works around this issue and should be safe to use even after upstream is fixed:
```python
import mpv
import time

player = mpv.MPV()
player.wait_for_property('idle-active')
player.playlist_append('http://rbb-fritz-live.cast.addradio.de/rbb/fritz/live/mp3/128/stream.mp3')
player.playlist_append('http://st01.dlf.de/dlf/01/128/mp3/stream.mp3')
player.playlist_pos = 1
print(player.playlist)
time.sleep(1)
print(player.playlist)
player.wait_for_playback()
```
As far as I understand this should not

**Comment by majuss** [comment]
Thank you, never expected I run into these kind of bugs while developing my radio :)
No I ran into the next challange... 
```python
import mpv
import time
import threading

def play_stream():
    player.wait_for_playback()
    print("Waiting ended")

player = mpv.MPV()
player.wait_for_property('idle-active') # Wait for mpv core to complete initialization

player.playlist_append('http://rbb-fritz-live.cast.addradio.de/rbb/fritz/live/mp3/128/stream.mp3')
player.playlist_append('http://st01.dlf.de/dlf/01/128/mp3/stream.mp3')
player_thread = threading.Thread(target=play_stream)
player_thread.start()

player.playlist_pos = 0
time.sleep(5)
player.pause = True
player_thread.join()
player.playlist_pos = 1
player.pause = False
player.wait_for_playback()
```
So this code starts the player in a forked thread and waits for the playback inside the forked thread. When I pause the playback and `.join()` the thread should die, but it doesn't work, it just hangs at join. How can I use the player in threads correctly?

**Comment by jaseg** [comment]
`join()` hangs because the thread hangs in `wait_for_playback()`. `wait_for_playback()` waits for mpv to [signal either shutdown or the end of the active file/stream](https://github.com/jaseg/python-mpv/blob/master/mpv.py#L643). Since you pause playback before the `join()` that never happens, and it hangs.

If you want to wait for the pause you can wait for the `core-idle` property. That property indicates whether the mpv player core is currently playing anything, without any regard for playlists or files or streams. Note that `core-idle` is also true for a while after calling `play()` while mpv is loading the stream. For that reason before starting the thread the example below waits for `core-idle` to become `False` once.
```python
#!/usr/bin/env python3
import time
import os
import sys
import threading

import mpv
player = mpv.MPV(ytdl=True)

def runner():
    while True:
        player.wait_for_property('core-idle') # wait for pause
        print('core-idle')
        time.sleep(1)

t = threading.Thread(target=runner)

player.play('https://www.youtube.com/watch?v=SkgTxQm9DWM')

player.wait_for_property('core-idle', lambda x: not x) # wait for stream to load
t.start()

paused = False
while True:
    input()
    paused = not paused
    player.pause = paused
    print('paused', paused)

sys.exit(0)
```
