### ISSUE TITLE
Fixes for use with Python2

### ISSUE THREAD

**Issue by fpp-gh** [jaseg/python-mpv#11]
For those who, like me, are stuck with Python 2 at the moment, and trying to make this work...

Initially, mpv wouldn't event import, but that was easy enough to fix:

- comment out the asyncio import (as it's not used any more)
- remove the 'daemon=True' kwarg in self._event_thread
- add a call to 'self._event_thread.setDaemon(True)' after that line

From there on, mpv imports, loads videos and most methods work:
command, terminate, seek, frame_step, loadfile/play, toggle_osd, show_text for example.
Haven't tested them all, but certainly enough to go by...

Thanks for these bindings !

**Comment by jaseg** [comment]
Fixed in 35de5ec . Making MPV inherit from object was missing from your list, otherwise the properties (most notably ```pause```) don't work.

Thank you for reporting this!

**Comment by fpp-gh** [comment]
I hadn't even noticed there were supposed to be properties, but so much the better, thanks :-)
