### ISSUE TITLE
Loading C Plugins

### ISSUE THREAD

**Issue by marnunez** [jaseg/python-mpv#113]
Hi! Quick question: will an instance of python-mpv load any C Plugin set up in the default folders? I'm specifically looking at the mpv-mpris C plugin (https://github.com/hoyon/mpv-mpris)

**Comment by jaseg** [comment]
That could work. There are a couple of places where libmpv behaves differently compared to mpv invoked from the command line though. The doc doesn't explicitely mention this so I'm not sure.

According to [the mpv documentation](https://mpv.io/manual/master/#c-plugins-location) in either case you should be able to load a C plugin throught the `--script` command-line option. You can pass that to the python-mpv constructor. That should work like this: `player = mpv.MPV(script="path/to/my_plugin.so")`


One thing to note loading C plugins is that the doc mentions at the moment these have to be explicitely enabled at compile-time. I can imagine some distros not yet doing that in their packages.

**Comment by jaseg** [comment]
I'm closing this now. Please comment if you have further quesions and I'll re-open it, or submit them as a new issue.

In case you got this working it would be awesome if you could share your steps for other people searching this bug tracker :smile:
