### ISSUE TITLE
How can I set 'cache' parameters?

### ISSUE THREAD

**Issue by project-owner** [jaseg/python-mpv#123]
Hi,

I'd like to set such parameters as --cache and --no-cache described here:
https://mpv.io/manual/master/#cache

How can I do that? It looks like the following configuration doesn't work:
{"audio-device": "alsa/default", "video": false, "cache": "no"}

Thanks in advance!

**Comment by jakeogh** [comment]
Searching thought these I see a few cache options, but no specific --no-cache. There is a --no-cache-pause.

https://github.com/mpv-player/mpv/blob/master/options/options.c
https://github.com/mpv-player/mpv/blob/master/options/m_option.h

**Comment by jaseg** [comment]
@jakeogh The cache options are defined in [demux/demux.c](https://github.com/mpv-player/mpv/blob/master/demux/demux.c).

@project-owner I tried the `cache` option with the following test script and it seems to work:
```python3
#!/usr/bin/env python3
import time
import sys
import binascii

import mpv

from PIL import Image, ImageDraw, ImageFont

player1 = mpv.MPV(log_handler=print, loglevel='debug')
player2 = mpv.MPV(log_handler=print, loglevel='debug', cache=False)

player1.loop = True
player2.loop = True
player1.play('test.webm')
time.sleep(1)
player2.play('test.webm')
while True:
    print('without arg:', player1['cache'], 'with arg:', player2['cache'])
    time.sleep(0.1)
sys.exit(0)
```
output:
```
[...]
without arg: auto with arg: False
v vo/x11/x11 Disabling screensaver failed (4). Make sure the xdg-screensaver script is installed.
without arg: auto with arg: False
without arg: auto with arg: False
without arg: auto with arg: False
without arg: auto with arg: False
v mkv EOF reached.
without arg: auto with arg: False
[...]
```

Why do you think your configuration does not work?

**Comment by project-owner** [comment]
According to this doc the value for the 'cache' should be no/yes/auto:
https://mpv.io/manual/master/#cache
Can you confirm that it should be boolean?
Thank you!

**Comment by jaseg** [comment]
Yes, that is ok. [python-mpv auto-converts `True`/`False` to `'yes'`/`'no'`](https://github.com/jaseg/python-mpv/blob/master/mpv.py#L589) since [it uses libmpv's string-based property api for most things](https://github.com/jaseg/python-mpv/blob/master/mpv.py#L1774) and there the convention is `'yes'`/`'no'`. In this case, you could pass any of `True, False, 'yes', 'no', 'auto'` and get well-defined behavior.
