### ISSUE TITLE
Configure seek bar to use bottom bar OSD

### ISSUE THREAD

**Issue by jakeogh** [jaseg/python-mpv#124]
I'm trying to make the LEFT/RIGHT seek bar use the nice new bottom bar OSD/OSC(?). This example has the bottom bar if it's moused-over, but hitting LEFT/RIGHT draws the seek bar in the middle of the video instead of using the bottombar. Using git-latest.

```python3
#!/usr/bin/env python3

import sys
import mpv


def logger(loglevel, component, message):
    print('[{}] {}: {}'.format(loglevel, component, message), file=sys.stderr)


def play(media):
    print("play('{}')".format(media), file=sys.stderr)

    player = mpv.MPV(ytdl=True,
                     log_handler=logger,
                     input_default_bindings=True,
                     input_vo_keyboard=True,
                     terminal=True,
                     input_terminal=True,
                     script_opts='osc-layout=bottombar,osc-seekbarstyle=bar',
                     osc=True)

    player.on_key_press('ESC')(player.quit)
    player.on_key_press('ENTER')(lambda: player.playlist_next(mode='force'))

    try:
        for item in media:
            player.play(item)
            player.wait_for_playback()
    except mpv.ShutdownError:
        pass

    player.terminate()

if __name__ == '__main__':
    play(media=['test.mkv'])
```

**Comment by jaseg** [comment]
What you're asking for is a known issue in mpv [[1]](https://github.com/mpv-player/mpv/issues/7891), [[2]](https://github.com/mpv-player/mpv/issues/3826). I found an only slightly hacky workaround until this gets fixed upstream:

```python3
#!/usr/bin/env python3

import sys
import mpv


def logger(loglevel, component, message):
    print('[{}] {}: {}'.format(loglevel, component, message), file=sys.stderr)


def play(media):
    print("play('{}')".format(media), file=sys.stderr)

    player = mpv.MPV(ytdl=True,
                     log_handler=logger,
                     input_default_bindings=True,
                     input_vo_keyboard=True,
                     terminal=True,
                     input_terminal=True,
                     osd_bar=False,
                     scripts='test.lua'
                     )

    player.on_key_press('ESC')(player.quit)
    player.on_key_press('ENTER')(lambda: player.playlist_next(mode='force'))

    try:
        for item in media:
            player.play(item)
            player.wait_for_playback()
    except mpv.ShutdownError:
        pass

    player.terminate()

if __name__ == '__main__':
    play(media=['LGR Plays - Goat Simulator-j4HY_fxwiZo.mp4'])
```
Put this lua script in the current working directory or somewhere else mpv can find it:
```lua
for key, loader in pairs(package.loaders) do
    res = loader('@osc.lua')
    print('res value', '"', res, '"', type(res))
    if type(res) == 'function' then
        print('found', res, res('@osc.lua'))
        break
    end
end

function seek_handler()
    show_osc()
end
mp.register_event("seek", seek_handler)
```

**Comment by jaseg** [comment]
To expand on this: The thing on the bottom is the "on-screen controller" (osc) and is drawn from mpv's included "osc.lua" script. The bar in the middle is part of the "on-screen display" (osd) and is drawn from mpv's core C code. Both are functionally independent pieces of code. What the above code does is it loads the built-in "osc.lua" script and patches in another event listener that will show it on seeks, automatically hiding it like with mouse movements.

**Comment by jakeogh** [comment]
Beautiful. That works perfect.

**Comment by pbaykalov** [comment]
@jaseg can you please tell somewhat more about how this scrpit should be used? I do not use Python MPV but I was searching for the solution of this annoying property of MPV.

**Comment by AndydeCleyre** [comment]
@pbaykalov I have saved that lua script as `~/.config/mpv/scripts/osc_on_seek.lua`, and that's enough for me. Is it any different if you pass the script as an option?

```console
$ mpv --script=~/.config/mpv/scripts/osc_on_seek.lua /path/to/video/file
```

**Comment by jaseg** [comment]
@pbaykalov If you are using mpv from the command-line as opposed to as a library, saving it to your user scripts as @AndydeCleyre wrote is the way to go.

@AndydeCleyre The reason I passed the script as an option in the code example is that when you use mpv as a library, you would not want to install this kind of script into a user's config. Instead, it would have to be kept as part of your program, and `--script` is a good way to do that.

**Comment by pbaykalov** [comment]
> What you're asking for is a known issue in mpv [[1]](https://github.com/mpv-player/mpv/issues/7891), [[2]](https://github.com/mpv-player/mpv/issues/3826). I found an only slightly hacky workaround until this gets fixed upstream:
> 
> ```python
> #!/usr/bin/env python3
> 
> import sys
> import mpv
> 
> 
> def logger(loglevel, component, message):
>     print('[{}] {}: {}'.format(loglevel, component, message), file=sys.stderr)
> 
> 
> def play(media):
>     print("play('{}')".format(media), file=sys.stderr)
> 
>     player = mpv.MPV(ytdl=True,
>                      log_handler=logger,
>                      input_default_bindings=True,
>                      input_vo_keyboard=True,
>                      terminal=True,
>                      input_terminal=True,
>                      osd_bar=False,
>                      scripts='test.lua'
>                      )
> 
>     player.on_key_press('ESC')(player.quit)
>     player.on_key_press('ENTER')(lambda: player.playlist_next(mode='force'))
> 
>     try:
>         for item in media:
>             player.play(item)
>             player.wait_for_playback()
>     except mpv.ShutdownError:
>         pass
> 
>     player.terminate()
> 
> if __name__ == '__main__':
>     play(media=['LGR Plays - Goat Simulator-j4HY_fxwiZo.mp4'])
> ```
> 
> Put this lua script in the current working directory or somewhere else mpv can find it:
> 
> ```lua
> -- emulate require() path search but load into current scope instead.
> -- osc.lua does not export a module table, so require would just return True.
> for key, loader in pairs(package.loaders) do
>     res = loader('@osc.lua')
>     print('res value', '"', res, '"', type(res))
>     if type(res) == 'function' then
>         print('found', res, res('@osc.lua'))
>         break
>     end
> end
> 
> function seek_handler()
>     show_osc()
> end
> mp.register_event("seek", seek_handler)
> ```

The Lua script you suggested prevents clicks on the bottom OSC bar BTW (I have recent-ish MPV).
