### ISSUE TITLE
Software renderer API

### ISSUE THREAD

**Issue by ghost** [jaseg/python-mpv#132]
mpv now has a software rendering API: https://github.com/mpv-player/mpv/blob/master/libmpv/render.h#L125

Basically, this is like the GL render API, except it does not use GL at all, and renders video to a user-provided memory buffer instead. The rest of the API is the same.

Can this be added to the wrapper?

The big problem is how to pass a memory buffer to it. (I myself would like to use it with cairo, which adds the problem of other Python wrapper to the mix, at least for me.)

**Comment by wm4** [comment]
PS: this API is slow of course, and anyone using it should be made aware that using GL or even just ``wid`` embedding is preferred. But I think it has some value because it's much simpler than messing around with GL.

**Comment by jaseg** [comment]
Just found this issue cleaning up old issues. python-mpv already has support for this API, see [the MPVRenderContext class](https://github.com/jaseg/python-mpv/blob/b5f03dd2b7d55b9a632c8771be4ae1a05c2f7fb8/mpv.py#L1820).
