### ISSUE TITLE
How to play other video formats from a URL?

### ISSUE THREAD

**Issue by jeanslack** [jaseg/python-mpv#133]
Hi, thanks for this very useful project.
I'm trying to implement python-mpv in a [wxPython GUI](https://github.com/jeanslack/Videomass) and would like to know if there is a way to play back a different video format, like in the corresponding mpv player:   

`$ mpv --ytdl-format=242 'https://www.youtube.com/watch?t=4&v=BaW_jenozKc'`   

or    

`$ mpv --ytdl-format=worst 'https://www.youtube.com/watch?t=4&v=BaW_jenozKc'`   

I've run the following example for now:   
```Python
import mpv
# Enable the on-screen controller and keyboard shortcuts
player = mpv.MPV(ytdl=True, input_default_bindings=True, input_vo_keyboard=True, osc=True)
player.play(url)
player.wait_for_playback()
player.terminate()
```
Later I will implement the code on a separate thread to not block the GUI.

**Comment by McSinyx** [comment]
Hello there, I think you can [supply `ytdl_format` to `MPV.__init__`](https://git.disroot.org/McSinyx/comp/src/commit/e860f1526d1a8b339b4184bfe30f25286d1fbfa9/comp#L82-L83).  I'm not sure how to change it within a running mpv instance though.

**Comment by jeanslack** [comment]
Thanks, that was what I was looking for ...but when I want to close the pseudo GUI of mpv it remains locked and does not close. It raise the following error:
```Python
raise ShutdownError('libmpv core has been shutdown')
mpv.ShutdownError: libmpv core has been shutdown
```

**Comment by jeanslack** [comment]
> Hello there, I think you can [supply `ytdl_format` to `MPV.__init__`](https://git.disroot.org/McSinyx/comp/src/commit/e860f1526d1a8b339b4184bfe30f25286d1fbfa9/comp#L82-L83). I'm not sure how to change it within a running mpv instance though.

I don't need to change it within a running mpv instance, just one file per instance and without embedding the mpv child in a wxPython frame.

Thank you very much, your help has been useful.
