### ISSUE TITLE
Additional possible embedding example for imgui-glfw

### ISSUE THREAD

**Issue by dfaker** [jaseg/python-mpv#143]
A quick sketch of playback, property access and update ui using render context embedding in pyhton imgui with glfw backend

https://github.com/dfaker/imgui_glfw_pythonmpv_demo

**Comment by jaseg** [comment]
Awesome! I've added you to the README in 5e581e817b79e15db814df9139057d1b78558e7a. If you would like to see anything changed, please feel free to send a PR against the README.

Thank you for the great demo!
