### ISSUE TITLE
 dll not found "mpv-1.dll"

### ISSUE THREAD

**Issue by bhong2002** [jaseg/python-mpv#151]
i downloaded a new version of mpv (mpv-x86_64-20210214-git-93066ff.7z) and there is no "mpv-1.dll"
error occurred:
mpv-1.dll not found

**Comment by jaseg** [comment]
I just checked their latest download (2021-03-17 x86-64 from the shinchiro Windows builds on sourceforge) and it does contain mpv-1.dll. Maybe their downloads were broken for a bit? Please try again, and feel free to re-open this issue if your issue persists.

Have a nice day!
