### ISSUE TITLE
How to realizate queue?

### ISSUE THREAD

**Issue by flusq** [jaseg/python-mpv#153]
I want music queue, not playlist. How to do what after music played, it deleted from playlist?

**Comment by jaseg** [comment]
You could put your queued files in a playlist, then use an [event callback](https://github.com/jaseg/python-mpv/blob/master/mpv.py#L1430) to wait for [END_FILE events](https://github.com/jaseg/python-mpv/blob/master/mpv.py#L267) and on END_FILE delete the first entry (index 0) in the playlist using [playlist_remove](https://github.com/jaseg/python-mpv/blob/master/mpv.py#L1159). You could also ignore mpv's playlist handling entirely and have your own queue that you schedule e.g. by using [wait_for_playback](https://github.com/jaseg/python-mpv/blob/master/mpv.py#L908) in a loop on a separate thread.

**Comment by jaseg** [comment]
I'm closing this issue because it seems it is resolved.
