### ISSUE TITLE
How can I handle circular buffer overruns when playing back multiple udp streams

### ISSUE THREAD

**Issue by gmckesey** [jaseg/python-mpv#16]
I have a program that is playing back multiple udp streams by calling the MPV constructor in a loop.  If my loop has enough streams, lets say 8 or more, I will eventually (after a few minutes of playback) get a message from the ffmeg module  'udp - Circular buffer overrun. To avoid, increase fifo_size URL option. To survive in such case, use overrun_nonfatal option'  from one of the instances.  The video playback hangs after this message is issued and no MPV events are issued.  If I wait long enough more instances will do the same thing.

I have increased the fifo_size and set the overrun_nonfatal flag to 1 by concatenating '?fifo_size=1000000&overrun_nonfatal=1' to the udp URL.  Unfortunately this only delays the problem and instead of getting a single message, I will get a flood of 'circular buffer overrun' messages. 

Assuming I don't add ovverrun_nonfatal=1 to the URL, I would like to just restart any stream that issues the error.  Unfortunately it doesn't seem like I can associate the ffmpeg message to a particular MPV instance.  I pass a logger function to the MPV constructor that is bound to an instance of a class that identifies the stream, but any messages logged by the ffmpeg component are handled by the instance logger that is passed by the first instantiation of the MPV instance, so I cannot programmatically track down which instance is actually issuing the 'circular buffer overrun' error.  It is, of course, obvious when you look at the video playback.

Some details w.r.t my code:

My MPV constructor is called from the constructor of a VideoWindow class and looks something like:

class VideoWindow(ttk.LabelFrame):
    def **init**(self, root_p, url_p, label_p):
        ttk.LabelFrame.**init**(self, root_p)
       self.url = url_p
       self.label = label_p
       self.player = mpv.MPV(log_handler = self.my_log_handler, msg_level='all=warn', ...)
       ...

```
def my_log_handler(self, loglevel, component, message):
    logger = logging.getLogger(__name__)
    if loglevel == 'error':
        emit = logger.error
    elif loglevel == 'warn':
        emit = logger.warn
    elif loglevel == 'info':
        emit = logger.info
    elif loglevel == 'fatal':
        emit = logger.fatal
    else:
        emit = logger.debug

    emit('{} [{}] - {}'.format(self.label, component, message))
```

...

Do you have any advice on how I might achieve my goal of restarting the errant stream?

**Comment by jaseg** [comment]
This sounds like either something is borked with your UDP sender (which may just be flooding your player with much more data than the player can handle), or your machine/video output config might be too slow to play the UDP stream in real time.

Have you tried playing the UDP stream in question with a regular ```mpv``` or ```mpv --msg-level=v```?

I can look further into this, but I would need to be able to reproduce this issue on my machine.

**Comment by jaseg** [comment]
Closing this issue, please reopen it if you have any further questions.
