### ISSUE TITLE
Greyscale conversion support

### ISSUE THREAD

**Issue by luisArandas** [jaseg/python-mpv#163]
Hello!

I'm not really sure if this is an issue/request/doubt, and for that I'm sorry in advance.

Does python-mpv support video greyscale conversion? I'm trying to play all the videos in monochromatic without really going through cv2 frame by frame. 

And if not is there any way around this? It doesn't seem very efficient in terms of computation doing something like that in the main thread.

Thanks in advance.

**Comment by neinseg** [comment]
Hey there!

python-mpv does not have anything built-in. However, the underlying libmpv has full support for ffmpeg filters, [link to doc](https://mpv.io/manual/master/#video-filters). [This stackoverflow post](https://stackoverflow.com/questions/32384057/ffmpeg-black-and-white-conversion) has details on desaturating using ffmpeg. In python-mpv you can apply this by passing `vf="hue=s=0"` to the MPV constructor.

I hope that helps!

**Comment by luisArandas** [comment]
Thank you very much @neinseg. Worked perfectly
