### ISSUE TITLE
can you use this with a running mpv instance if so how

### ISSUE THREAD

**Issue by TingTingin** [jaseg/python-mpv#165]
hi i was under the impression than this was a tool for controlling a running mpv instance im trying to create an mpv script and thought would be of help but it seems i was confused so im asking can you use this with a running mpv instance if so how

**Comment by neinseg** [comment]
No, you cannot. This python library is a wrapper around [libmpv](https://mpv.io/manual/master/#embedding-into-other-programs-libmpv), and does not currently address mpv's IPC interface. Have a look at [this project](https://github.com/iwalton3/python-mpv-jsonipc), which should be able to control a running mpv instance through its IPC interface. Note that I haven't used that project before, so I can't vouch for it.

**Comment by TingTingin** [comment]
yeah thanks im trying it now it seems to be what i was looking for
