### ISSUE TITLE
Clarify use of threading in README, please

### ISSUE THREAD

**Issue by ssokolow** [jaseg/python-mpv#17]
You should really mention that event handlers are run on a separate thread managed by the library.

My first impression, before my perfectionism drove me to examine your code, was that player.wait_for_playback()` was equivalent to something like `QApplication._exec()` or `gtk.main()` and that event handlers would only run on the main thread and only after that was called.

**Comment by jaseg** [comment]
Fixed in eb8b6a0. As a small bonus, you now can also call the constructor with ```start_event_thread=False``` and call the resulting object's ```._loop``` function yourself. That acts much like ```gtk.main```. If for some reason you don't like threading at all, there is an out-of-date branch on this repo that contains python3 asyncio-based handling of events (which I ripped out because it was unportable and really awkward to use at no benefit).

**Comment by ssokolow** [comment]
Thanks. While I'd consider renaming `._loop` since it's no longer being presented as a private method, what you've done so far definitely resolves this.

Once I have time to work this into some of my projects as a replacement for an awkward, organically overgrown "call mpv in a subprocess once per file" system, I'll probably offer up a few improvements to the docs to cover what I learn from poking at it more.

**Comment by rr-** [comment]
I can no longer see the `asyncio` branch

**Comment by jaseg** [comment]
True. I wonder where that went. I must have deleted it during some rebasing action. If you really need it, I can pull it out of an old backup.

**Comment by rr-** [comment]
Looks like the event thread plays nice with my script which leverages `asyncio`, so I won't be needing it - I was mostly curious what it looked like.

Anyway, the README file still refers to that branch, so you might want to correct that.
Thanks

**Comment by jaseg** [comment]
Done.

The basic layout was that ```libmpv``` has some function that produces a sort of event fd that gets a single byte written to or something on every event received, and you could pass that into asyncio's event loop to wake up the event handler on every event.

**Comment by jaseg** [comment]
Thank for the report :smile_cat:
