### ISSUE TITLE
`mpv-1.dll` to path Instruction

### ISSUE THREAD

**Issue by alexpandain** [jaseg/python-mpv#174]
I read the Readme and downloaded libmpv on my windows also added libmpv folder to path but still showing error abt `mpv-1.dll`
Please tell step by step correctly how to add `mpv-1.dll` to path

**Comment by neinseg** [comment]
As the README says, you can put that dll e.g. next to your `python.exe` or next to `mpv.py`. Where did you put it and how did you call your script? Please post the terminal output.

**Comment by alexpandain** [comment]
> As the README says, you can put that dll e.g. next to your `python.exe` or next to `mpv.py`. 

Thanks,I put it on python dir. and its not throwing `mpv-1.dll` error anymore
