### ISSUE TITLE
can i use python-mpv with Kivy Library ?

### ISSUE THREAD

**Issue by Goyp95** [jaseg/python-mpv#175]
How to import mpv player to kivy screen, any ideas? winId or winfo_id don't work ..

**Comment by neinseg** [comment]
If X11 embedding does not work, OpenGL may be an option. Kivy [seems to have OpenGL API support](https://kivy.org/doc/stable/examples/gen__3Drendering__main__py.html). [Here] is an example of python-mpv embedding using OpenGL. [Here] is another example of python-mpv embedded into imgui via OpenGL, which I think is similar to your use case.

**Comment by Goyp95** [comment]
Hey neinseg, thank for reply but the link [Here] that you gave don't work.

**Comment by neinseg** [comment]
Hmm, not sure what's up with github there. Here's the target URL:

https://github.com/dfaker/imgui_glfw_pythonmpv_demo/blob/main/main.py

**Comment by jaseg** [comment]
https://github.com/dfaker/imgui_glfw_pythonmpv_demo/blob/main/main.py
