### ISSUE TITLE
Test failures with mpv 0.34

### ISSUE THREAD

**Issue by sebastinas** [jaseg/python-mpv#187]
As of mpv 0.34 we are noticing test failures in `python-mpv`'s testsuite on Debian's [autopkgtest](https://ci.debian.net/data/autopkgtest/testing/armhf/p/python-mpv/16918048/log.gz) infrastructure. While debugging the issue I was able to pinpoint the segfault to `test_write`. Writing to the `colormatrix-primaries` seems to cause the issue (but I have also seen crashes when writing to other properties, so I'm not sure if this property is the actual issue).

**Comment by baldurmen** [comment]
I can reproduce this issue on my Debian machine, trying to build the (previously working) Debian package, both with python3.9 and python3.10. This is not the first time `test_write` has caused us issues (see https://github.com/jaseg/python-mpv/issues/108)

Skipping `colormatrix-primaries` in `test_write` as proposed by @sebastinas doesn't seem to fix the problem:

```
diff --git a/tests/test_mpv.py b/tests/test_mpv.py
index b9120c0..0527e87 100755
--- a/tests/test_mpv.py
+++ b/tests/test_mpv.py
@@ -108,7 +109,7 @@ class TestProperties(MpvTestCase):
         check_canaries = lambda: os.path.exists('100') or os.path.exists('foo')
         for name in sorted(self.m.property_list):
             # See issue #108 and upstream mpv issues #7919 and #7920.
-            if name in ('demuxer', 'audio-demuxer', 'audio-files'):
+            if name in ('demuxer', 'audio-demuxer', 'audio-files', 'colormatrix-primaries'):
                 continue
             # These may cause files to be created
             if name in ('external-file', 'heartbeat-cmd', 'wid', 'dump-stats', 'log-file') or name.startswith('input-'):
```

```
test_write (tests.test_mpv.TestProperties) ... Segmentation fault
E: pybuild pybuild:354: test: plugin distutils failed with: exit code=139: python3.9 setup.py test 
```

Maybe the debug work done in this Debian bug report can be helpful? https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1000255

While waiting for a patch, I'll just skip `test_write` in Debian, as I used to :) As always, happy to test things out.

**Comment by sebastinas** [comment]
`colormatrix-primaries` was the first that failed for me. I don't know if there are any others.

**Comment by baldurmen** [comment]
I can confirm version `1.0.1` fixes the testsuite problems we had with `test_write`!

**Comment by baldurmen** [comment]
@jaseg again, this has been fixed and this issue can be closed :)
