### ISSUE TITLE
Raspberry pi libEGL error

### ISSUE THREAD

**Issue by BurlyLlama28** [jaseg/python-mpv#190]
When I run simple script with `wait_until_playing` func I got this:
ligEGL warning: DRI2: failed to authenticate

And nothing happens actually
Can you help me?

**Comment by jaseg** [comment]
From googling around this seems to be caused by some version conflict in your installed OpenGL libs. The easiest workaround will be to simply use `MPV(vo='x11')`, forcing X11 video output.
