### ISSUE TITLE
Streaming record support

### ISSUE THREAD

**Issue by silvioprog** [jaseg/python-mpv#191]
Hi.

First, thanks for this awesome project!

So, is there any option to start a streaming record?

For example, using the `mpv` command line tool, we can record a streaming into a output file:

```bash
mpv http://s1.myradiostream.com:12508/listen.mp3 --stream-record=record.mp3
```

It would be really a useful feature! 

cheers

**Comment by silvioprog** [comment]
Ping https://github.com/mpv-player/mpv/issues/9625

**Comment by silvioprog** [comment]
@dfaker, firstly, thanks a lot for this information, it worked and will help me a lot!

So, I have another question. To stop the only the recording without stop the radio, I'll use this (ugly) code (that works fine):

```python
player.stream_record = ''
```

Is this a proper way to stop a recording and keep the streaming playing?

**Comment by dfaker** [comment]
That doesn't strike me as a distasteful solution at all.

**Comment by silvioprog** [comment]
Thanks again for the additional info, @dfaker. I'm going to use it. :+1:
