### ISSUE TITLE
mpv-2.dll support?

### ISSUE THREAD

**Issue by LeiYangGH** [jaseg/python-mpv#192]
In sourceforge download page, there's already mpv-2.dll, but the python code still hardcodes `mpv-1.dll`.

**Comment by ArjixWasTaken** [comment]
mpv-1.dll can be found [here](https://sourceforge.net/projects/mpv-player-windows/files/libmpv/mpv-dev-x86_64-20210801-git-416668d.7z/download) (64bit)

**Comment by ArjixWasTaken** [comment]
I think this issue should be pinned, as it has a download link that took me a lot of time to find, and it would save other's time.

**Comment by borro0** [comment]
This issue should be fixed now right?
https://github.com/jellyfin/jellyfin-mpv-shim/issues/246 mentions it is fixed

**Comment by jaseg** [comment]
@borro0 you are right, starting with commit 341f4c5c161d91d92a43fe7061657c46d2b3b934 which is part of python-mpv v1.0.1 both `mpv-1.dll` and `mpv-2.dll` are supported.
