### ISSUE TITLE
ValueError: ('Invalid value for mpv parameter', -4, ...

### ISSUE THREAD

**Issue by BurlyLlama28** [jaseg/python-mpv#193]
when I run a couple of video on raspberry pi and then turn by key .playlist_play_index(0) - it gives me that error
Can you help me please?

**Comment by qbe** [comment]
Same Issue here,
```
pi@raspberrypi:~ $ mpv -V
mpv 0.34.0 Copyright © 2000-2021 mpv/MPlayer/mplayer2 projects
 built on UNKNOWN
FFmpeg library versions:
   libavutil       56.70.100
   libavcodec      58.134.100
   libavformat     58.76.100
   libswscale      5.9.100
   libavfilter     7.110.100
   libswresample   3.9.100
FFmpeg version: 4.4.1
```
```
pi@raspberrypi:~ $ sudo lsof -p 489 | grep mpv
python3 489   pi  mem    REG      179,2  1767868  41489 /usr/lib/arm-linux-gnueabihf/libmpv.so.1.107.0
```
turns out my libmpv was outdated, so i had to manually add the `deb-multimedia` repository and install `libmpv1` even tho it was already installed. The Joy of working with debian.

**Comment by BurlyLlama28** [comment]
@qbe I have this issue on raspberry pi os, do you know how to update libmpv1 there?

**Comment by qbe** [comment]
check what version of libmpv1 your distro has in which repository, add that repository, manually install libmpv1 to update libmpv1, and thats probably it

**Comment by BurlyLlama28** [comment]
@qbe I have libmpv1 version 0.32.0-3. What version of libmpv1 worked for you?

**Comment by BurlyLlama28** [comment]
It seems kinda a problem, because 0.32.0 is the latest version for raspberry pi os

**Comment by BurlyLlama28** [comment]
Like really I don't know what to do :(

**Comment by qbe** [comment]
have you checked deb-multimedia ?

**Comment by qbe** [comment]
or check any other repository than the default raspbian one

**Comment by qbe** [comment]
i cannot help you any further then

**Comment by BurlyLlama28** [comment]
@jaseg Maybe you can explain: why I have this issue?

**Comment by BurlyLlama28** [comment]
@jaseg I really need your help. It's important to me

**Comment by neinseg** [comment]
Hey there,
The guess by @qbe that this may be due to a version mismatch is probably right.

Could it be that you updated your mpv package (that has the ```mpv``` binary) but did not update your libmpv package (that has ```libmpv.so```)? If I remember correctly debian has these two in two separate packages that can be updated independently.

You can check the libmpv version your python script is loading by printing the return value of ```mpv.MPV().mpv_version```, e.g. using:

```python3
python3 -c 'import mpv; print(mpv.MPV().mpv_version)'
```
