### ISSUE TITLE
embedded mpv window does not work on wayland.

### ISSUE THREAD

**Issue by kanehekili** [jaseg/python-mpv#196]
Having mpv integrated into a pyqt5 app the window floats freely - outside the app.   Size can't be controlled.
If starting with QT_QPA_PLATTFORM=wayland the following error is shown:

`Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
qt.qpa.plugin: Could not find the Qt platform plugin "wayland" in ""
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, xcb.
`
 mpv based "celluloid" crashes while trying to create an GL context - something I don't do. Looks like an upstream problem

Any idea if that is solvable?

**Comment by trin94** [comment]
The window id method doesn't work for Wayland since there is no window id for each widget anymore.

You need to make use of the renderer api functionality as seen here: https://github.com/feeluown/FeelUOwn/blob/master/feeluown/gui/widgets/mpv.py

**Comment by kanehekili** [comment]
Right - works perfectly. Thanks a lot. Closing issue ...
