### ISSUE TITLE
Where do i find libmpv.so 

### ISSUE THREAD

**Issue by RoboTomi7** [jaseg/python-mpv#201]
i keep getting the error Could not find module 'libmpv.so' when trying to import this module 

ive already tried downloading it from https://sourceforge.net/projects/mpv-player-windows/ and it gives me a file called libmpv.dll.a and even with that it dosent work, i realize the file extensions are differnt so out of hope that itll work i changed the ending to .so and to no surprise, same error. ive also tried older versions of mpv and those have not worked either.

edit: using windows 10 os

**Comment by dfaker** [comment]
Given it's looking for a .so file, I assume you're not using Windows?

**Comment by RoboTomi7** [comment]
sorry i didnt specify in my comment, i am using windows 10

**Comment by jaseg** [comment]
For installation on Windows, checkout [this issue comment](https://github.com/jaseg/python-mpv/issues/60#issuecomment-352719773). `libmpv.so` is for Linux, on Windows you need `mpv-1.dll`. You have to download that separately from the same place you get your mpv from.
