### ISSUE TITLE
Yocto libmpv.so not found

### ISSUE THREAD

**Issue by adityasingh1993** [jaseg/python-mpv#203]
I have build mpv on yocto, and it's working totataly fine. But when I am trying to use python-mpv i am getting exception. Issue is mostly because of libmpv.so not found. How to get libmpv.so for yocto?
P.S: I am using the yocto for Raspberrypi3b+

**Comment by jaseg** [comment]
python-mpv uses [`ctypes.util.find_library`](https://docs.python.org/3/library/ctypes.html#finding-shared-libraries) from the python standard lib to look for libmpv. Make sure your LD_LIBRARY_PATH is set up correctly, and that libmpv.so is installed in the correct location.

**Comment by adityasingh1993** [comment]
@jaseg libmpv.so is not present in the build image. When i tried to installed it using debian package for arm64,i got lot of other packages dependency issue. Is there any bitbake recipie for libmpv.so available or any other help regarding this?

**Comment by jaseg** [comment]
Oh, I see. Building it using yocto should be possible, but will take some effort. A quick google search yielded some existing bitbake recipes for mpv ([1](https://git.openembedded.org/meta-openembedded/tree/meta-oe/recipes-multimedia/mplayer/mpv_0.32.0.bb?id=5af46f89fcef5c436786ed81978de60f26abe054), [2](https://git.congatec.com/yocto/meta-openembedded/blob/7d399caee6adc82812f631f756b7805d866bad83/meta-oe/recipes-multimedia/mplayer/mpv_0.15.0.bb)), that you may be able to base your work off.

**Comment by adityasingh1993** [comment]
@jaseg  These are also for building mpv, they haven't included the libmp.so in there build. I think libmpv.so build is not included on the mention link.

**Comment by jaseg** [comment]
Yes, you'll have to modify those to your needs and turn on building libmpv.
