### ISSUE TITLE
Contradictory license information

### ISSUE THREAD

**Issue by mgorny** [jaseg/python-mpv#206]
Right now the project has some contradictory information regarding its license:

- the notices on top of Python files indicate that their content is covered by GPL-2+
- `license` in `setup.py` says GPL-3+
- trove classifiers say GPL-2+ and LGPL-2+

Could you please clarify which one is correct, and fix the remaining instances?

**Comment by jaseg** [comment]
True, I typo'ed the one in setup.py. Originally, python-mpv was licensed under AGPLv3+. I have since changed over the license to match mpv's license, which is your choice of GPLv2+ or LGPLv2+. I'll fix setup.py to say GPLv2+, since I don't know how to set multiple licenses there.

**Comment by jaseg** [comment]
Yes, that is correct. When you use it along an LGPL libmpv, python-mpv is also LGPL.

**Comment by ChrisLambert1** [comment]
Thank you for that answer, but as an improval it would be great, if this would be stated in the header of the mpy.py file.

It will be appreciated, if there would be a reference that it is possible to use your module under LGPL, depending on the used license for mplayer.
So why not just putting a brief intro in the header of mpv.py, as it's done in your GitHub repository -> License:
"
python-mpv inherits the underlying libmpv's license, which can be either GPLv2 or later (default) or LGPLv2.1 or later. For details, see [the mpv copyright page](https://github.com/mpv-player/mpv/blob/master/Copyright).
"
and extend it by:
"Depending on the license used in combination with mplayer, the same license is applicable for this piece of code."
"Uses license agreements could be found in:
License.GPL
or
License.LGPL
"

Or make it easier:

Just extend / enter a header (s. epydoc definition) after the module description in the mpv.py file including possible licenses:

__author__ = "You"
__copyright__ = "Copyright 2007, The Project"
__credits__ = ["to who is involved"]
__license__ = "GPLv2+", "LGPLv2+"
__version__ = "x.x.x"
__maintainer__ = "***"
__email__ = "myMail"
__status__ = "Release"

Regards,
Chris
