### ISSUE TITLE
Getting PID of mpv player

### ISSUE THREAD

**Issue by sdpsachin** [jaseg/python-mpv#214]
HI, 
I want to get the pid of mpv on the terminal of ubuntu. However, it is not returning anything after passing the command as 

"ps aux | grep mpvplayer"

Even I tried multiple process names for mpv

MPV/mpv/mpvplayer2/mpvplayer3.

So can somebody suggest me how I can get pid of MPVplayer on the terminal?

**Comment by jaseg** [comment]
mpv shows up as `mpv` in process listings. For me, `ps aux|grep mpv` works.

Note that this is the issue tracker for python-mpv, a python binding for libmpv. The actual mpv player development happens over at https://github.com/mpv-player/mpv/
