### ISSUE TITLE
Invalid `None` default for `level` in `show_text`

### ISSUE THREAD

**Issue by The-Compiler** [jaseg/python-mpv#226]
Doing:

```python
import mpv
player = mpv.MPV()
player.show_text("Hello World!")
```

with python-mpv 1.0.1 and mpv 0.34.1 results in:

```
ValueError: ('Invalid value for mpv parameter', -4, (<MpvHandle object at 0x7fe8ec233e40>, <mpv.LP_MpvNode object at 0x7fe8eb99c3c0>, <mpv.LP_MpvNode object at 0x7fe8eb99c340>))
```

which seems to happen due to the `level=None` here:

https://github.com/jaseg/python-mpv/blob/20ec2a74b8c407e1fcaabb1554a4acd83bb57bb9/mpv.py#L1393

when instead using:

```python
player.show_text("Hello World!", level=1)
```

it works fine.

**Comment by trin94** [comment]
I can confirm that this issue exists.

```shell
❯ mpv --osd-level=help
Valid values for option osd-level are:
    0
    1
    2
    3
```

Changing the level default parameter from `None` to `0` fixes the issue.
