### ISSUE TITLE
Unable to set geometry option 

### ISSUE THREAD

**Issue by phkarmur** [jaseg/python-mpv#236]
[py_log.txt](https://github.com/jaseg/python-mpv/files/9706590/py_log.txt)

Unable to set geometry option in X11 screen
Tried using `player['geometry']` and `player._set_property("geometry", geometry)` but no luck!

**Comment by jaseg** [comment]
What behavior did you expect and what behavior did you get?

Please also post a link to your code or a testcase.

**Comment by phkarmur** [comment]
my mistake, i was using `player.fullscreen = True` thats why it was playing in whole screen 
sorry for your inconvenient

        def my_log(loglevel, component, message):
            print('[{}] {}: {}'.format(loglevel, component, message))

        player = mpv.MPV(log_handler=my_log)`

        #player.fullscreen = True
        player.loop_playlist = 'inf'
        geometry = str(args.w) + 'x' + str(args.h) + '+' + str(args.x) + '+' + str(args.y)
        player['geometry'] = geometry
        print(geometry)
        player.set_loglevel('debug')
        player['geometry'] = geometry
        player['osd-msg1'] = 'MPV Python test!'


        player.play(args.i)
        player.wait_until_playing()

        del player
