### ISSUE TITLE
Please migrate away from setup.py

### ISSUE THREAD

**Issue by baldurmen** [jaseg/python-mpv#240]
Hello!

`setup.py` has been deprecated for a while now (although support hasn't yet bet removed). It would be nice if this project moved away from it before something actually breaks :)

If you want to stick with `setuptools`, newer versions do support buidling via a PEP517-style `pyproject.toml` file:

https://setuptools.pypa.io/en/latest/userguide/pyproject_config.html

Otherwise, I'm myself partial to `flit`.

Cheers,

**Comment by jaseg** [comment]
Thank you for the PR!

I had a look at flit, but it did a bit too much magic for a package as simple as this one.
