### ISSUE TITLE
Smooth video switching

### ISSUE THREAD

**Issue by renat2985** [jaseg/python-mpv#242]
How to make smooth video switching? For example, fade out and in when you switch a video file.
Is it possible?

**Comment by jaseg** [comment]
You can to do that using an lavfi-complex. Have a look at [this issue](https://github.com/jaseg/python-mpv/issues/167) and [this StackOverflow post](https://stackoverflow.com/questions/72014088/ffmpeg-lavfi-is-it-possible-to-fade-out-an-image-overlay-that-was-loaded-with-a). The relevant python-mpv options are "lavfi_complex" and "external_files", both directly mapped from mpv, for how they work check out the [mpv man page here](https://mpv.io/manual/master/#options-lavfi-complex). Both options can be passed to python-mpv's `loadfile` method.

**Comment by jaseg** [comment]
Feel free to open another issue if you have further questions.
