### ISSUE TITLE
Passing Command-Line Options Directly To MPV?

### ISSUE THREAD

**Issue by hendursaga** [jaseg/python-mpv#243]
Suppose I had a script that, like in bash and most other POSIX tools, stopped processing options past `--`, the so-called [end of options convention](https://wiki.bash-hackers.org/dict/terms/end_of_options). How might I pass those unprocessed options directly to `mpv`? I see `MPV`'s constructor has `extra_mpv_flags` as well as `extra_mpv_opts`, but that would mean I'd have to do some processing, no? I can't just pass a string. How do I get around this?

**Comment by jaseg** [comment]
You could use `extra_mpv_opts`. I don't think you should have to do any processing, you just have to remove the leading dashes and put them in an `{option: value}` dict like this:

```python
extra_options = {'fullscreen': 'yes', 'keep-open': 'yes'}
player = mpv.MPV(..., **extra_options)
```
