### ISSUE TITLE
typo in the latest git tag name?

### ISSUE THREAD

**Issue by baldurmen** [jaseg/python-mpv#246]
Hi!

Thanks for the latest batch of fixes :)

I see you've released tag [vv1.0.3](https://github.com/jaseg/python-mpv/releases/tag/vv1.0.3) and it kinda looks like a typo... Nothing major but I thought you should know!

**Comment by jaseg** [comment]
Yup, I mis-handled the release script. I'll delete the bad tag and push a properly-formatted one later today.

**Comment by jaseg** [comment]
I have updated the tag. Thank you for the report!
