### ISSUE TITLE
Please replace unmaintained xvfbwrapper (e.g. with PyVirtualDisplay)

### ISSUE THREAD

**Issue by mgorny** [jaseg/python-mpv#249]
[xvfbwrapper](https://github.com/cgoldberg/xvfbwrapper) is no longer maintained — it has no commit activity since 2019, it has annoying race conditions and nobody to merge the fixes. Would you consider replacing it with another package?

My personal recommendation would be [PyVirtualDisplay](https://github.com/ponty/PyVirtualDisplay) — it is actively maintained and uses a more robust approach to starting Xvfb (`-displayfd`). If you agree, I can prepare a pull request doing the replacement.

We'd like to remove xvfbwrapper entirely from Gentoo.

**Comment by jaseg** [comment]
Sounds good. If you'd open a PR that would be awesome, else I'll do it when I have capacity.

**Comment by mgorny** [comment]
Done. It seems that it was a drop-in replacement here ;-).

**Comment by mgorny** [comment]
That said, I do wonder why you're calling Xvfb from within tests, if you run the whole test suite inside a Xvfb in the CI pipeline anyway.

**Comment by jaseg** [comment]
The reason for the per-test Xvfb-wrapper is for when you run the tests locally. Otherwise when you run the testsuite it looks like you just navigated to a pirate website without an adblocker.

**Comment by mgorny** [comment]
> The reason for the per-test Xvfb-wrapper is for when you run the tests locally. Otherwise when you run the testsuite it looks like you just navigated to a pirate website without an adblocker.

Hmm but a "global" instance of Xvfb for the whole of the test suite (started via `conftest.py`) would work for that as well, wouldn't it?

**Comment by jaseg** [comment]
You're right, that would probably work too and might save a few seconds per run. I'll try it out the next time I mess around with the unit tests.
