### ISSUE TITLE
can not set class object instance method as handler

### ISSUE THREAD

**Issue by cosven** [jaseg/python-mpv#26]
I have a piece of code like this:

```python
import mpv

player = mpv.MPV(ytdl=True, input_default_bindings=True, input_vo_keyboard=True)

class T(object):
    def t(self, *args, **kw):
       print(args, kw)

t =  T()
# Property access, these can be changed at runtime
player.observe_property('time-pos', t.t)   # this will raise AttributeError
```
It will try to set `observed_mpv_properties` attr on handler, but as the [python docs](http://docs.python.org/3/library/stdtypes.html#methods) say:
> setting method attributes on bound methods is disallowed. Attempting to set an attribute on a method results in an  AttributeError being raised.

**Comment by jaseg** [comment]
Hmm, that is kind of bad. It will also try to put a unregister function in an attribute. I will try to figure out something. In the meantime, try ```player.observe_property('time-pos', lambda *a, **kw: t.t(*a, **kw))```.

**Comment by McSinyx** [comment]
I'm not sure if this hack OK (I don't understand the *put a unregister function in an attribute* part) but how about a handler wrapper? I.e. `def handler_wrapper(*args, **kwargs): handler(*args, **kwargs)`. Sorry it isn't mean to fix anything, just a question to improve my Python knowledge.

**Comment by cosven** [comment]
`lambda *a, **kw: t.t(*a, **kw))` is also a handler wrapper, which is more simple and elegant, i think.

**Comment by McSinyx** [comment]
I meant in [`MPV.observe_property`](https://github.com/jaseg/python-mpv/blob/b1f81ac56184a172f093b0a640890de9ded405d7/mpv.py) we create a handler wrapper and use it instead of the handler itself. Also may you explain the problem further to me?

**Comment by cosven** [comment]
It seems that I misunderstood your proposal. I had thought you were suggesting the user defining a handler wrapper.

As to your proposal, if we simply use a handler wrapper, we can not know if a function is registered or not because we only set attribute on handler wrapper but not the handler.

Anyway, in long term, I think **set an attribute on a method to identify whether a function is registered** is not a very good way, which is not a common usage.

**Comment by jaseg** [comment]
I'm thinking about just removing that unregister attribute for ```observe_property``` but leaving it in for the ```@property_observer``` decorator. A decorator setting attributes on the returned wrapper function has precedence in the standard library with ```functools.lru_cache```.

**Comment by cosven** [comment]
I have another problem that is related to this one.
There is a class like the following:

```
class Player(object):
    def __init__(self):
        self._mpv = mpv.MPV()
```

And I want to register a event_callback, but I can not find a good way to do this.
I found there were two ways to register event_callback

one: use `register_event_callback` function
two: use `mpv.event_callback('event_str')` decorator

But in this case, I can not set decrotor with `self._mpv.event_callback`, I have to do some trick to implement this.
@jaseg

**Comment by jaseg** [comment]
The original issue is fixed now as I propsed [here](https://github.com/jaseg/python-mpv/issues/26#issuecomment-303027280), and a regression test has been added.
