### ISSUE TITLE
Gapless playback not always working

### ISSUE THREAD

**Issue by santaclose** [jaseg/python-mpv#262]
I'm using this in [my project](https://github.com/santaclose/qmp) and everything works fine except transitions between songs are sometimes noticeable. Maybe you know if there is a flag or something I can pass somewhere to make it work consistently?
Thanks in advance and also for your work on this.

**Comment by jaseg** [comment]
That's awesome!

I briefly looked into this, and sadly it seems that the upstream mpv project is unwilling to add nice transitions between playlist entries: https://github.com/mpv-player/mpv/issues/4512

**Comment by santaclose** [comment]
I was talking about gapless playback, which as far as I understand is different from crossfading? 🤔 
Thanks for looking into it anyway.
