### ISSUE TITLE
python-mpv not finding libmpv DLL on MSYS2

### ISSUE THREAD

**Issue by gpraceman** [jaseg/python-mpv#263]
I am running Python 3.10 on Windows 10 via MSYS2, with GTK3 for the UI.  I have python-mpy 1.0.3 installed.  I also installed the mingw-w64-x86_64-mpv package to MSYS2.  That installs libmpv-2.dll, mpv, mpv.com, and mpv.exe files to the mingw64\bin folder.  When I try to import mpv with my Python code, I get the "Cannot find mpv-1.dll or mpv-2.dll in your system %PATH%" error, so something is wrong with my setup.  Any guidance would be appreciated.

**Comment by jaseg** [comment]
I mean, did you check what `%PATH%` gets passed to python? Is mingw64\bin in there?

**Comment by gpraceman** [comment]
Yes, I have C:\msys64\mingw64\bin at the top of my path variables, which is the location for my MSYS2 environment.  There is no mpv-1.dll or mpv-2.dll in that folder, only libmpv-2.dll.  

Maybe it is just as simple as renaming libmpv-2.dll to mpv-2.dll.  I did try that and was able to run an AVI file but I tried several of the examples at https://pypi.org/project/python-mpv/.  Some did nothing, some errored out.  So, not sure that the renaming of the DLL file is the correct solution or not.

**Comment by jaseg** [comment]
Did you install the python you ran this with through msys2 too? If not, that would be likely to cause issues.

**Comment by gpraceman** [comment]
The only way I could get GTK3, which is the UI framework that I use for all of my projects, to run on Windows is via MSYS2.  That is also where I setup Python.  

If mpv-2.dll and libmpv-2.dll are the same, then a renaming of the file to get rid of the error would be the trick.  I would just have to remember that whenever I do an update.

**Comment by gpraceman** [comment]
The files that you pointed me to has the DLL being named libmpv-2.dll

**Comment by jaseg** [comment]
I'm putting out a release adding the filename libmpv-2.dll to the search list. I think it once was named mpv-2.dll and they just renamed it.
