### ISSUE TITLE
Couldn't get examples to run

### ISSUE THREAD

**Issue by Matt-Deacalion** [jaseg/python-mpv#27]
Hi,

I had no luck getting the examples from the README to run. No exceptions were thrown and no errors were reported. I'm running `Python 3.6.1` and `MPV 0.25.0`.

Regards,
Matt

**Comment by jaseg** [comment]
You can try adding a ```mpv.set_loglevel('debug')``` along with ```log_handler=print``` in the ```MPV``` constructor. That will produce lots of debug output that may give a hint at what's wrong.

The examples in the readme do play youtube videos via youtube-dl (do you have that and lua installed along with mpv?). Loading a video through youtube-dl may take several seconds (>10 depending on your internet connection!) during which nothing appears to happen.

**Comment by Matt-Deacalion** [comment]
Thank you, with your help I got it working. I'm still having problems when I try to create a keybinding though.

```
Traceback (most recent call last):
  File "./main.py", line 18, in <module>
    player.register_key_binding('q', my_q_binding)
  File "/home/matt/projects/mpv/mpv.py", line 844, in register_key_binding
    callback_or_cmd.mpv_key_bindings = getattr(handler, 'mpv_key_bindings', []) + [keydef]
NameError: name 'handler' is not defined
```

**Comment by jaseg** [comment]
Oops, I think I broke that with one of my latest commits. The new key binding interface does not yet have adequate unit test coverage. Try again with the current master.

**Comment by McSinyx** [comment]
Hi there, I notice that since c47bd2a2c603c57c2c86474450056f21492cce48, `MPV.observe_property`'s `handler` takes exactly 2 arguments. I created PR #25 but didn't get any response.

BTW @jaseg I think you should have vim configured to distinguish tab and spaces because line 39, 76 and 77 in `README.md`.

**Comment by jaseg** [comment]
@Matt-Deacalion is this still an issue or can we close this?

**Comment by Matt-Deacalion** [comment]
I fixed it, thank you! :smile:
