### ISSUE TITLE
The PyPI package is not up to date

### ISSUE THREAD

**Issue by lgbaldoni** [jaseg/python-mpv#274]
As per subject, the package in the [repository](https://pypi.org/project/python-mpv/) is still at 1.0.5.

**Comment by jaseg** [comment]
Thank you for the report. I built the packages, but just forgot to upload them. They're up on PyPI now.

**Comment by lgbaldoni** [comment]
@jaseg PyPI still has 1.0.5. Is there a vetting process?

**Comment by jaseg** [comment]
Oops, sorry. The PyPI project was renamed from "python-mpv" to "mpv" a while ago. I forgot to upload a build to the old project, and didn't realize that's what you're talking about. Both projects are up-to-date now. I should add a depreciation notice to the old alias.
