### ISSUE TITLE
SyntaxError on Mac os with python3 on v1.0.6

### ISSUE THREAD

**Issue by Kai0711er** [jaseg/python-mpv#278]
I am using python 3.7 on MacOS Sonoma and I am getting the following Syntax Error on Import:

```
Traceback (most recent call last):
  File "lib/player.py", line 1, in <module>
    import mpv
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/mpv.py", line 896
    if (m := re.search(r'(\d+)\.(\d+)\.(\d+)', self.mpv_version)):
          ^
SyntaxError: invalid syntax
```

**Comment by jaseg** [comment]
Your Python is too old. Python 3.7 is more than 6 years old, and hasn't gotten even security fixes for almost a year now.

**Comment by Kai0711er** [comment]
I know, thought it would work with 3.7 as its stated in the docs... I am testing with 3.7 as I need it for an existing embedded project. I will probably look towards other solutions. Thanks!
