### ISSUE TITLE
libmpv1 version outdated python-mpv 1.107

### ISSUE THREAD

**Issue by cluemaster-robert** [jaseg/python-mpv#287]
when installing stage packages for snaps ( -python-mpv ), im getting this error:

**"python-mpv requires libmpv with an API version of 1.108 or higher (libmpv >=0.33), but you have an older version 1.107"**

but 1.107 is the latest version on https://pypi.org/project/python-mpv/

**Comment by jaseg** [comment]
The version listed at https://pypi.org/project/python-mpv/ refers to python-mpv, not libmpv, and is 1.0.7, not 1.107.
