### ISSUE TITLE
When should I call this method ‘mpv.terminate()’

### ISSUE THREAD

**Issue by lzy-zj** [jaseg/python-mpv#289]
for example:
```

class MpvWidget(QWidget):
    def __init__(self, parent=None):
        super().__init__(parent)
        self.player = MPV(
            wid=str(int(self.winId())),

            log_handler=None,
            loglevel='debug'
        )

        # if i use this method, MpvWidget will not call __del__
        self.mpv.observe_property(
            'time-pos',
            lambda name, position: self._on_position_changed(position)
        )

    def __del__(self):
        self.player.terminate()
```

**Comment by jaseg** [comment]
You don't have to call terminate at all in this case. The underlying mpv instance is automatically destroyed when the MPV object is garbage collected. You only have to call terminate yourself when for some reason you want libmpv to release resources like window handles or when using OpenGL before the MPV object is automatically garbage collected.
