### ISSUE TITLE
Update PyPI repo

### ISSUE THREAD

**Issue by McSinyx** [jaseg/python-mpv#29]
[The PyPI repo](https://pypi.python.org/pypi/mpv) is quite outdated now, can you please continue uploading this amazing module?

> Seriously though, part of the idea of this being all in one handy file is that you can just copy it into your project.

I'm not sure if you recognize your module is quite useful and widely used as it's really is, but please spend some time doing this. It'd be awesome if we can just `pip install mpv` or, even cooler, if it's possible to use it as a dependency via `install_requires=['mpv']` in `setup.py`'s `setup`. There is even [a fork](https://github.com/Aninstance/python-mpv-zws) just to upload the updated module (but it's dead now).

Thanks a lot.

**Comment by jaseg** [comment]
[Here you go.](https://pypi.python.org/pypi/python-mpv)

**Comment by jaseg** [comment]
I'll try to gain ownership of the 'mpv' package too.

**Comment by McSinyx** [comment]
Thank you very much :bowing_man:
