### ISSUE TITLE
http header field

### ISSUE THREAD

**Issue by burat-ni-junjun** [jaseg/python-mpv#294]
help please
does someone know here how can i add custom header, i cant see any function about it on "mvp.py" and not on command line

like this 

import mpv
player = mpv.MPV()
player.set_http_headers()

thankssssss

**Comment by burat-ni-junjun** [comment]
never mind i figure it out

**Comment by NexusSfan** [comment]
How

**Comment by jaseg** [comment]
Generally, everything you can access through an mpv option or property is mapped on the interface. These mappings are created at runtime according to the loaded libmpv, so they're not explicitly listed in mpv.py. You can list these properties using python-mpv, or just have a look at the libmpv documentation.
