### ISSUE TITLE
Please add observe_property function

### ISSUE THREAD

**Issue by Frechdachs** [jaseg/python-mpv#3]
It would be great if this interface would implement the observe_property function. Or is there already something that provides similar functionality?

**Comment by jaseg** [comment]
done. Use it like this:
```python
player = mpv.MPV()

def handler(property_change_event):
    print(property_change_event['name'], property_change_event['value'])

player.observe_property('paused', handler)
```

**Comment by jaseg** [comment]
One note of caution: The player signals the property change via an event. This means the handler is called in a blocking fashion from the event handling thread spawned internally.

**Comment by Frechdachs** [comment]
Thank you!
