### ISSUE TITLE
Looks to only support Python 3.x?  

### ISSUE THREAD

**Issue by SpootDev** [jaseg/python-mpv#31]
Should probably state that in your documentation if that's the case.

**Comment by jaseg** [comment]
There is a [somewhat outdated but functional branch](https://github.com/jaseg/python-mpv/tree/py2compat) with python 2 compatibility.

**Comment by jaseg** [comment]
I have added a blurb in the README. Thanks for the report!

**Comment by SpootDev** [comment]
Thanks.
