### ISSUE TITLE
Missing method: self._register_message_handler_internal

### ISSUE THREAD

**Issue by xplwowi** [jaseg/python-mpv#38]
Hi, 
Please try to run advanced example no. 1. You won't be able to register key binding because of missing method.
This method is referenced twice in mpv.py

**Comment by jaseg** [comment]
Thanks for the report. I don't know how that slipped through the cracks. I guess a couple of regression tests would be in order there. Fixed in master and v0.2.6 on pypi.

**Comment by jaseg** [comment]
I'll close this issue now. If it has not been resolved, please just re-open it. Thank you!
