### ISSUE TITLE
Question. Embedding the player in an application

### ISSUE THREAD

**Issue by jmoraleda** [jaseg/python-mpv#42]
Hello, I have been testing python-mpv for a project. Thank you for creating it!. I would like to create a wxPython (phoenix) widget to encapsulate the play window and be able to display that window as part of a larger application, but have not figured out how to tell python-mpv to open the player inside an existing window rather than on its own window. Is this possible with python-mpv? I am in Linux. Could you post an example on how to pass the window handle? Thank you again.

**Comment by jaseg** [comment]
Have a look at (libmpv#methods-of-embedding-the-video-window)[https://github.com/mpv-player/mpv-examples/tree/master/libmpv#methods-of-embedding-the-video-window]. The easiest way would be to pass the ```wid``` option to the ```MPV``` constructor. The OpenGL API is wrapped in python-mpv, but there is no high-level support for it.

**Comment by jaseg** [comment]
Also, maybe have a look at [this](https://github.com/Frechdachs/mpvQC/blob/master/mpvQC.py)

**Comment by jmoraleda** [comment]
Thank you. Setting the wid option works. Before I was passing wid as an int instead of a str and that is why the player would not open embedded.
