### ISSUE TITLE
register_key_binding disables dragging of the VO window

### ISSUE THREAD

**Issue by ssokolow** [jaseg/python-mpv#45]
I was in the middle of porting a little helper script from calling mpv as a subprocess to using `python-mpv` so I could track per-file playback completion without having to re-create the window every time and I ran across an interesting bug.

As soon as I added even a single call to `MPV.register_key_binding`, the borderless window I was using ceased to be draggable.

I managed to track the problem down to [line 975](https://github.com/jaseg/python-mpv/blob/master/mpv.py#L975), and applied the following patch to my local copy of `mpv.py`:

```diff
- self.command('enable-section', binding_name)
+ self.command('enable-section', binding_name, 'allow-vo-dragging')
```

I'd offer a pull request, but I've also made several changes to restore Python 3.4 compatibility and I don't have a quick and easy way to tease apart multiple diff hunks into separate branches and doing it just for that one line doesn't feel worth the effort.

**Comment by jaseg** [comment]
Thank you for the report. It seems mpv is internally always using this and ```allow-hide-cursor```, so I have now added both.

Feel free to send a pull request with your python3.4 compatibility fixes (doesn't matter if it's all in one big commit). I'd then put that on a separate branch for the record.
