### ISSUE TITLE
loadfile doesn't seem to do anything

### ISSUE THREAD

**Issue by nivekuil** [jaseg/python-mpv#5]
```
import mpv
player = mpv.MPV()
player.loadfile("/home/nivekuil/test.flv")
```

Nothing happens when I run this - no mpv processes are created, and the program exits immediately. The file plays correctly when I run mpv from the command line.

Tested on Python 3.5.1, mpv 0.15.0, Arch Linux.

**Comment by jaseg** [comment]
Are you running this from a python shell or from a standalone script? In case of the latter, try adding ```player.wait_for_playback()``` at the end. Otherwise playback will be started, but immediately stopped again as the host process exits.

**Comment by nivekuil** [comment]
That did the trick, thanks.
