### ISSUE TITLE
v0.3.4 incompatible with mpv v0.14.0 due to _handle_key_binding_message

### ISSUE THREAD

**Issue by jonbobbly** [jaseg/python-mpv#51]
I get this error:

`Traceback (most recent call last):
  File "/home/jonathon/Documents/Inbox/py-mpv/mpv.py", line 462, in _event_loop
    message_handlers[target](*args)
TypeError: _handle_key_binding_message() missing 1 required positional argument: 'key_name'
`
When I try to use the 'q' keybinding from the last example in the readme.

**Comment by jaseg** [comment]
That error is likely due to an incompatibility between your ```python-mpv``` and ```libmpv``` versions. Which versions of both are you using?

**Comment by jonbobbly** [comment]
The python-mpv is the latest from the master branch. I'm not sure how to check which libmpv version I have, but `mpv --version` reports version 0.14.0.

**Comment by jaseg** [comment]
Okay, there's your problem. [v0.14.0](https://github.com/mpv-player/mpv/releases/tag/v0.14.0) is a super-ancient version from like two years ago. Try either getting a recent ```libmpv``` or use a similarly ancient version of ```python-mpv```. [This one](https://github.com/jaseg/python-mpv/tree/f3cab6cdf1298e78133ce157835e14f44da7047a) might work.

This module is not really supposed to work against really old ```libmpv```s so I'll close this issue. If you have any further questions, feel free to ask, though.

**Comment by jonbobbly** [comment]
I found a ppa for a version of mpv from august 12th of 2017, but the issue is still there. Perhaps ubuntu 16.04 LTS is more "long-in-the-tooth" and less "supported," and I should just upgrade.

**Comment by jaseg** [comment]
I'd rather try downgrading ```python-mpv```. You could in theory try compiling a recent ```libmpv```, but AFAIR they dropped support for older ```ffmpeg``` versions and that'd mean you'd likely get cascading dependency problems on any LTS distro. Apart from some convenience functions there have not been any *major* functional improvements of ```python-mpv``` since ```libmpv``` v0.14.0 and only small convenience fixes so going with an old version of ```python-mpv``` IMHO is not that bad.
