### ISSUE TITLE
Can't import mpv with Python 2.7

### ISSUE THREAD

**Issue by FreeSlave** [jaseg/python-mpv#55]
`python-mpv-0.3.6` installed via pip

```
Traceback (most recent call last):
  File "testmpv.py", line 1, in <module>
    import mpv
  File "/usr/local/lib/python2.7/dist-packages/mpv.py", line 449
    target, *args = devent['event']['args']
            ^
SyntaxError: invalid syntax
```

**Comment by McSinyx** [comment]
Have you read the [README](https://github.com/jaseg/python-mpv#python-27-35-or-36-officially)?

**Comment by FreeSlave** [comment]
I read. It says that master does not support python 2. Nothing about the fact that 0.3.6 version does not support it too.

**Comment by McSinyx** [comment]
I believe `master` branch and 0.3.6 are currently the same now. The section I pointed to says you have to use the [`py2compat`](https://github.com/jaseg/python-mpv/tree/py2compat) branch to have Python 2 support. That could be simply archive by downloading [this](https://github.com/jaseg/python-mpv/raw/py2compat/mpv.py) or:

```sh
git clone https://github.com/jaseg/python-mpv
cd python-mpv
git checkout py2compat
```

**Comment by FreeSlave** [comment]
Ok, thanks.
> I believe master branch and 0.3.6 are currently the same now
The minimum version that abandoned python 2 support should be specified then, instead of master (which is not constant entity anyway).
