### ISSUE TITLE
Add Youtube DL options support

### ISSUE THREAD

**Issue by GalaxyLJGD** [jaseg/python-mpv#58]
You could add Youtube DL options such as changing the video format or even give options using `--ytdl-raw-options`, it would be very useful for certain scripts to choose predefined formats.

Sorry for my bad English.

**Comment by McSinyx** [comment]
That's already supported under the name of [option access](https://github.com/jaseg/python-mpv#advanced-usage). You could either do it at initation (e.g. `mp = MPV(ytdl_format='best')`) or like in the given link.

**Comment by GalaxyLJGD** [comment]
Oh, I had not seen it, but is it possible to do something similar to `--ytdl-format=244+bestaudio`? because I can not make it work well.

Excuse me if I ask silly questions, I'm a novice in programming.

**Comment by McSinyx** [comment]
I'm afraid that `244+bestaudio` is not a valid format. It can only be either a format code (244), or an expression describing the format (bestaudio), not both.

**Comment by GalaxyLJGD** [comment]
Now it works, thanks for the help.

**Comment by McSinyx** [comment]
I'm glad to here so. If everything runs fine, please close the issue. Thanks.

**Comment by arrudagates** [comment]
Apparently ytdl_raw_options doesn't work, i'm trying to use --no-cache-dir because that's a fix from their issues section.

**Comment by jaseg** [comment]
The following works:

```
import mpv                                                                                                              
player = mpv.MPV(ytdl = True, log_handler=print, loglevel='debug', ytdl_raw_options='foo=bar,baz=23')
player.play('https://www.youtube.com/watch?v=SkgTxQm9DWM')
```

You can see that the correct options are passed to youtube-dl in the console debug output. Direct passthrough of python dicts as MPV node objects indeed seems to be broken, but the fall-back to passing command-line strings is ok I think.

You can also change this option at runtime, AFAICT with the updated arguments being used for the next youtube-dl invocation:

```
player['ytdl-raw-options'] = 'foo=bar,baz=42'
```
