### ISSUE TITLE
AttributeError: 'module' object has no attribute 'MPV'

### ISSUE THREAD

**Issue by diamond-lizard** [jaseg/python-mpv#67]
After doing:
```
import mpv
player = mpv.MPV()
```
I get:
```
AttributeError: 'module' object has no attribute 'MPV'
```
A little introspection shows:
```
>>> dir(mpv)
['CallbackThread', 'Context', 'EOFReasons', 'EndOfFileReached', 'Errors', 'Event', 'Events', 'InputDispatch', 'LogLevels', 'LogMessage', 'MPVError', 'OpenGLContext', 'Property', 'Semaphore', 'Thread', '_CAPI_MAJOR', '_CAPI_MINOR', '_MIN_CAPI_MINOR', '_REQUIRED_CAPI_MAJOR', '_ReplyUserData', '__author__', '__builtins__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__spec__', '__test__', '__version__', '_errors', '_is_py3', '_strdec', '_strdec_err', '_strenc', 'sys']
>>> mpv.__doc__
'pympv - Python wrapper for libmpv\n\nlibmpv is a client library for the media player mpv\n\nFor more info see: https://github.com/mpv-player/mpv/blob/master/libmpv/client.h\n'
```
I had installed python-mpv using: `pip3 install --user python-mpv`, and I'm using python3.4 on Gentoo Linux.

**Comment by McSinyx** [comment]
For some reasons, python-mpv isn't fully compatible with Python 3.4 and below. I think you should try to upgrade your Python (and may I ask why you're using such an out-dated version on a rolling-release distro like Gentoo?).

**Comment by jaseg** [comment]
I'm closing this, as I'm not supporting Python 3.4. If you find a fix for this that is not compromising readability or functionality, I'd be open to a pull request.
