### ISSUE TITLE
Selecting screen on which video will be played

### ISSUE THREAD

**Issue by airmonitor** [jaseg/python-mpv#75]
Hello.

This is not strict issue, but more general question.
I'm trying to run website using cherrypy to display videos on connected monitor via hdmi.
When I'm using your example code, no video is showing.
From my remote ssh session I'm running:

mpv --fs-screen=0 --vo=rpi https://www.youtube.com/watch?v=x_Akn8fUBeQ which do the trick.

Therefore I'm wondering if you have included --fs-screen option to your script bcs frankly didn't noticed this in your work.

Regards
Tom.

**Comment by McSinyx** [comment]
Have you tried using `__setattr__`? This beautiful API simply parses options to libmpv:

```python3
from mpv import MPV

mp = MPV(input_default_bindings=True, input_vo_keyboard=True, ytdl=True)
mp['fs-screen'] = 0
mp.cycle('fullscreen')
mp.play('https://www.youtube.com/watch?v=x_Akn8fUBeQ')
```

**Comment by jaseg** [comment]
@McSinyx is correct

I'm closing this now. If you have any more questions, feel free to reopen this if related or open another ticket.
