### ISSUE TITLE
no-video option

### ISSUE THREAD

**Issue by joeyism** [jaseg/python-mpv#81]
In mpv, you can specify `--no-video` to turn off the video and stream only the audio. How can you do that with python-mpv? I've tried
```python
import mpv
player = mpv.MPV("no-video")
```
and
```python
import mpv
player = mpv.MPV()
player["no-video"] = True
```
but nothing seem to work

**Comment by jaseg** [comment]
As documented in the [mpv man page](https://mpv.io/manual/master/#options-vid) you can't use `--no-video` through the client API. Either `mpv.MPV(video=False)` or `mpv.MPV(vid=False)` works.
