### ISSUE TITLE
is there any way to play video loaded to memory using python-mpv?

### ISSUE THREAD

**Issue by redstoneleo** [jaseg/python-mpv#86]
Any way to play bytes object in python-mpv? For example , how to  play the contents in Axel in the following ?
```
File1 = open('vid.webm','rb')
Axel  = File1.read()
```

**Comment by jaseg** [comment]
The obvious way would be mpv's ```memory://``` protocol, but I'd advise against that for anything beyond a few megabytes. You could try stuffing it into some mmap'ed shm buffer and shove the fd into mpv using the ```fd://``` protocol but it'd be hard to get one of those in python. I think I'd do this by simply dumping the bytes into a [named temporary file](https://docs.python.org/3/library/tempfile.html#tempfile.NamedTemporaryFile) and simply playing that.

**Comment by redstoneleo** [comment]
Thanks ! Is it easy to implement that  dumping the bytes into an io.BytesIO object and then playing it ?

**Comment by jaseg** [comment]
BytesIO works with python's ```read``` and ```write```, but doesn't give you an fd that you could pass into libmpv.
