### ISSUE TITLE
Where is the 'libmpv.so' file??

### ISSUE THREAD

**Issue by BlueHorn07** [jaseg/python-mpv#87]
In Requirement section, I should have '**libmpv.so**' file. But, I can't find it and how to use it.

I have a trouble in 'import mpv' command.
I already do 'pip install python-mpy', and checked it really have been stalled.
So, I guess it's matter of no libmpv.so file.

Does anyone know how to solve this problem??

**Comment by jaseg** [comment]
If you're using linux you get this file by installing a package named something like "libmpv" or "mpv-libs" or "mpv-devel".

**Comment by BlueHorn07** [comment]
I'm not using Linux... just using Widow OS. Then, should I install Linux OS to operate this python code?

**Comment by jaseg** [comment]
I just typed "windows libmpv" into google and this came up: https://mpv.srsfckn.biz/

Looks like you'll have to download the "dev" archive. There will be a ```libmpv.dll``` in it. Just use a python script or shell in the same directory you extracted that archive to and it will find the dll.

**Comment by jaseg** [comment]
Here's another place where you can get (more up-to-date) libmpv builds for windows: https://sourceforge.net/projects/mpv-player-windows/files/

I don't know enough about windows to help you with properly installing that though. If python can't find the library, make sure your python shell or script runs in the same directory the library is in.

**Comment by BlueHorn07** [comment]
![image](https://user-images.githubusercontent.com/51858327/59575033-a53a6b80-90f4-11e9-818d-7d2c5ac655ae.png)
I attach what I'm suffering now. If anyone know the solution please share it for me....

**Comment by BlueHorn07** [comment]
> Here's another place where you can get (more up-to-date) libmpv builds for windows: https://sourceforge.net/projects/mpv-player-windows/files/
> 
> I don't know enough about windows to help you with properly installing that though. If python can't find the library, make sure your python shell or script runs in the same directory the library is in.

Oh, Thank you for your help! :) I'll try that. Have a good day~~

**Comment by BlueHorn07** [comment]
I successfully handle this problem!!
I download .dll file from this link(https://mpv.srsfckn.biz/ )
And i used all just files in 'i686' folder.

When i didn't use 'i686', there're some errors like,
"OSError: [WinError 193] %1 is not a valid Win32 application."
and "OSError: [WinError 126] Cannot find the specified module."

But, they were all solved when i use files in 'i686' :)

**Comment by jaseg** [comment]
Thank you for the update! I'm glad you got it working. Since the issue seems fixed, I'll close it now. If you have further questions, feel free to re-open this issue or open a new one.

**Comment by xuzhaozheng** [comment]
how can a macOS user get libmpv.so ?

**Comment by ssebastianoo** [comment]
> 
> 
> Here's another place where you can get (more up-to-date) libmpv builds for windows: https://sourceforge.net/projects/mpv-player-windows/files/
> 
> I don't know enough about windows to help you with properly installing that though. If python can't find the library, make sure your python shell or script runs in the same directory the library is in.

but there isn't any .so file there

**Comment by Su-HengZhang** [comment]
For Debian Linux, you can try: apt install libmpv-dev

**Comment by jaseg** [comment]
> how can a macOS user get libmpv.so ?

@xuzhaozheng From https://mpv.io/installation/ it looks like you have to use macports or homebrew.

**Comment by zillydev** [comment]
Anyone found a solution for macOS?
