### ISSUE TITLE
(custom) keypress detection errors

### ISSUE THREAD

**Issue by rien333** [jaseg/python-mpv#93]
Custom keypress detection, and possibly also the detection of (some) default keypresses, seems to be broken. Given the following example code from the README:

``` python
...
@player.on_key_press('q')
def my_q_binding():
    print('THERE IS NO ESCAPE')
...
```

I get this error when pressing <kbd>q</kbd>:

``` python-traceback
TypeError: _handle_key_binding_message() takes from 3 to 4 positional arguments but 5 were given
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/mpv.py", line 474, in _event_loop
    message_handlers[target](*args)
TypeError: _handle_key_binding_message() takes from 3 to 4 positional arguments but 5 were given

```

## System info ##

``` shellsession
$ uname -mor
5.3.13-arch1-1 x86_64 GNU/Linux
$ mpv --version
mpv 0.30.0-210-g7c6570402b Copyright © 2000-2019 mpv/MPlayer/mplayer2 projects
 built on Tue Nov 26 11:50:51 CET 2019
ffmpeg library versions:
   libavutil       56.35.101
   libavcodec      58.62.100
   libavformat     58.35.100
   libswscale      5.6.100
   libavfilter     7.66.100
   libswresample   3.6.100
ffmpeg version: N-95734-gbfa8272f40


```

I tested this with python-mpv from git master.

**Comment by jaseg** [comment]
This is due to the upstream change in https://github.com/mpv-player/mpv/commit/21f2468d67e11eff7ede0d85fa6f4ab5c4f7de84 . I've fixed this in master and published v0.4.0 on PyPI. The fix is compatible with older mpv versions.

Thank you very much for your detailed report!

**Comment by rien333** [comment]
Wow, thanks for the super quick fix! 

Possibly on topic: I remember being able to send the python-mpv module key presses  right from the terminal. Key press detection now works again when a video is in focus, but when I'm e.g. playing an audio file in a terminal app, I have no way to control mpv (which I'm pretty sure did work a little while ago). 

I'm creating the mpv object with `player = mpv.MPV(input_default_bindings=True, input_vo_keyboard=True)`, FYI, and I'm running python-mpv with the commits you just pushed.

If I'm wrong, and the terminal was never able to straightforwardly send keypresses to a mpv instance via this module (i.e. by just registering `@player.on_key_press('SPACE')`),  then what is the recommended way to detect keypresses from the terminal?

**Comment by jaseg** [comment]
I'm not sure if that ever worked. I just tried `--input-terminal` and that didn't seem to work. Probably the best way to do this would be to grab raw terminal key presses using something like [this](https://www.jonwitts.co.uk/archives/896), then mapping to [mpv key names](https://github.com/mpv-player/mpv/blob/master/DOCS/man/input.rst#key-names), then use the `keypress` [input command](https://github.com/mpv-player/mpv/blob/master/DOCS/man/input.rst#list-of-input-commands) via `mpv.command`.

Another, easier way to control audio playback would be to use `--input-vo-keyboard' and simply force a window with `--keep-open=always` and `--force-window'.

**Comment by rien333** [comment]
Weird, I swear it once worked, but oh well. Thanks for your method, I'll try it now.

**Comment by jaseg** [comment]
It might be that at some point libmpv grabbed stdin and did actually handle input like that. I just couldn't find any references changing in the mpv repo. Technically it would be possible.

**Comment by jaseg** [comment]
#122 contains a solution to this. The trick is to use both `terminal=True` and `input_terminal=True` when initializing libmpv.
