### ISSUE TITLE
Implement stream_cb?

### ISSUE THREAD

**Issue by ripdog** [jaseg/python-mpv#94]
Hello,

Thanks for python-mpv, it's very useful. 

Is there any chance you could implement the stream_cb API, described at https://github.com/mpv-player/mpv/blob/master/libmpv/stream_cb.h ?

I'm currently stuck for a good way to stream audio files both to disk and to play them at the same time, this could be a way for me to do that.

Thanks again.

**Comment by jaseg** [comment]
A draft for that just landed on master in 3ee682c4edd7ad8582d92412f05048bf9d0afe61. You can use `player.register_stream_protocol` to provide a fully custom stream implementation, or use the `@python_stream(name, size)` and `@python_stream_catchall` decorators on a generator to make a stream from a python generator. Here's some test code I used:
```python3
#!/usr/bin/env python3
import time
import os
import sys
import threading

import mpv

def my_log(loglevel, component, message):
    print('[{}] {}: {}'.format(loglevel, component, message))

player = mpv.MPV(#log_handler=my_log, loglevel='trace',
        input_default_bindings=True, input_vo_keyboard=True,
        input_terminal=True)
@player.python_stream_catchall
def catchall(fn):
    def reader():
        with open(fn, 'rb') as f:
            while True:
                chunk = f.read(1024)
                if not chunk:
                    break
                yield chunk
    return reader, None
print('registered')
time.sleep(1)
player.play('python://test.webm')
time.sleep(1)
#player.play('test.webm')
print('playing')
player.loop = 'inf'
player.wait_for_playback()
print('terminating')
player.ter#!/usr/bin/env python3
import time
import os
import sys
import threading

import mpv

def my_log(loglevel, component, message):
    print('[{}] {}: {}'.format(loglevel, component, message))

player = mpv.MPV(#log_handler=my_log, loglevel='trace',
        input_default_bindings=True, input_vo_keyboard=True,
        input_terminal=True)
@player.python_stream_catchall
def catchall(fn):
    def reader():
        with open(fn, 'rb') as f:
            while True:
                chunk = f.read(1024)
                if not chunk:
                    break
                yield chunk
    return reader, None
print('registered')
time.sleep(1)
player.play('python://test.webm')
time.sleep(1)
#player.play('test.webm')
print('playing')
player.loop = 'inf'
player.wait_for_playback()
print('terminating')
player.terminate()
```

**Comment by jaseg** [comment]
In reply to your original problem: You could feed the data into mpv through a pipe/fifo via `fd://` URIs.

**Comment by ripdog** [comment]
Ahhh! Thank you very much! You're an absolute treasure.

Now I can hopefully get gapless playback of streamed music working!

Re: `fd://`, I considered that but as I understand it, that only works on unix-likes.

**Comment by ripdog** [comment]
In the `stream_cb` definition, it says
>A return of 0 will be interpreted as final EOF, although libmpv might retry the read

However, `read_backend()` breaks when an int is returned from my `read()`. Is the correct implementation to return `b'0'`? Perhaps this should be documented?

Other than that, I'm very happy with this implementation. I've implemented it in my program, and it works great. (This is the third time I've rewritten my mpv control layer, and the first time it's worked properly.)

So thanks again :)

**Comment by jaseg** [comment]
Thank you, well spotted. v0.4.1 here and up on pypi now includes all of this functionality with only small changes, and has fixed docstrings

**Comment by jaseg** [comment]
btw, the README now includes a basic usage example as well.
