### ISSUE TITLE
f-string compatibility with Python 3.5

### ISSUE THREAD

**Issue by xgi** [jaseg/python-mpv#95]
Hey, thanks for the library; it's been working really well for me.

I noticed in a recent update that my builds starting failing with Python 3.5. I think the culprit is just an f-string on [this line](https://github.com/jaseg/python-mpv/blob/91067fcbd89c92cbeac2532473d687220040ec0a/mpv.py#L1256), which are 3.6+:
```python
raise KeyError(f'Python stream name "{name}" is already registered')
```

**Comment by jaseg** [comment]
Oh. :woman_facepalming:

Version 0.4.2 just hit master and PyPI and should be compatible. Thank you for the quick report.
