### ISSUE TITLE
You forgot to push to PyPi!

### ISSUE THREAD

**Issue by ripdog** [jaseg/python-mpv#97]
PyPi is still 0.4.3.

**Comment by ripdog** [comment]
Although it looks like I won't be able to use the pypi version anyway. Adding the script directory to path, either by `os.environ` or `sys.path` is not propagated to `mpv.py`. I don't seem to have a choice but to include `mpv.py` manually.

**Comment by McSinyx** [comment]
Since this whole thing starts to get complicated, could we just have the DLL be specified while initializing the MPV object?  I understand this would need much refactoring.

**Comment by ripdog** [comment]
@McSinyx Don't worry. After my current PR gets applied, you will simply have to add the mpv dll path to `os.environ['PATH']` before importing mpv.

**Comment by jaseg** [comment]
Gah! I could have sworn I did! Fixed. :woman_facepalming:

**Comment by jaseg** [comment]
> Since this whole thing starts to get complicated, could we just have the DLL be specified while initializing the MPV object? I understand this would need much refactoring.

The issue with that is that libmpv might be imported in several places, and you can only ever load a shared library once. You can't reasonably unload it, and you can't reasonably have two versions of it loaded at the same time (and expect things to not utterly break).

**Comment by jaseg** [comment]
Library loading should be fixed now on master and v0.4.5, which I double-checked I actually uploaded to PyPI :)

**Comment by ripdog** [comment]
Thanks again, @jaseg . Hopefully now I'll be able to stop pestering you :)
