### ISSUE TITLE
Usage of opengl-cb client API is deprecated

### ISSUE THREAD

**Issue by trin94** [jaseg/python-mpv#99]
As of release `v0.29.0` the usage of opengl-cb API is deprecated:
https://github.com/mpv-player/mpv/releases/tag/v0.29.0
https://github.com/mpv-player/mpv/blob/5feee11e43a0907306db1df993cf1cd11c8596d9/libmpv/opengl_cb.h#L22

The replacement for opengl-cb should be the "render" API.

https://github.com/mpv-player/mpv/blob/master/libmpv/render.h

**Comment by jaseg** [comment]
I've pushed some initial work-in-progress code for an API in cd3c3a7. It's still untested, but you can try it already if you want. I'll try finishing this week.

**Comment by jaseg** [comment]
Check it out: https://gist.github.com/jaseg/657e8ecca3267c0d82ec85d40f423caa (works with current master)

**Comment by jaseg** [comment]
I've also added some deprecation warnings to the legacy opengl_cb functions. Feel free to test the new API, and please report any problems in their own issues. I will push these changes to PyPI once I feel they have stabilized and once I have at least some unit test coverage.
